### ISSUE TITLE
Scrolls to incorrect position on Firefox when using anchor link

### ISSUE THREAD

**Issue by andrew-ireland** [swup/scroll-plugin#19]
Hi Georgy, congrats on the refactor of Swup — it appears really well thought out! I really like the plugin architecture especially.

I've just built a new site using this version, but in testing have noticed that when using an anchor link from another page the Scroll Plugin isn't hitting the correct spot in Firefox. It scrolls to the correct position in Safari and Edge.

I'm using the following options (the issue occurs with doScrollingRightAway set to false as well):
```
    new SwupScrollPlugin({
      doScrollingRightAway: true, // default false
      scrollFriction: .35, // default 0.3
      scrollAcceleration: 0.04, // default 0.04
    })
```

Could this be a bug, or is there some sort of user error on my behalf I'm missing? Happy to provide a link to my staging site if that's helpful.

Thanks for your help.

**Comment by daun** [comment]
The issue seems to be gone in recent Firefox versions; I'll close this for now. If anyone is still seeing this problem, feel free to reopen.
