### ISSUE TITLE
A11y: allow disabling animated scroll from visit object

### ISSUE THREAD

**Issue by daun** [swup/scroll-plugin#63]
**Describe the feature**

- Add a `visit.scroll.animate` key that gets set right on `visit:start` by this plugin
- Allow other plugins (mainly a11y-plugin) to unset the flag and disable animations

**Alternatives considered**

- Use the existing suggested solution with `matchMedia`
- As a user, I'd prefer having an option on the a11y-plugin to group such behavior in one place

**How important is this feature to you?**

- [x] Nice to have
- [ ] Would make my life a lot easier
- [ ] I cannot use swup without it

**Comment by hirasso** [comment]
Nice! Great idea. The visit object is unlocking a lot of previously hard-to-slove features 🗝️
